In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB # Gaussian Naive Bayes
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier #stochastic gradient descent
from sklearn.tree import DecisionTreeClassifier


In [2]:
train_df =pd.read_csv('http://bit.ly/kaggletrain')
test_df =pd.read_csv('http://bit.ly/kaggletest')

In [3]:
train_df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [4]:
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [5]:
train_df = train_df.drop(['Ticket', 'Cabin'], axis=1)
test_df = test_df.drop(['Ticket', 'Cabin'], axis=1)
combine = [train_df, test_df]

In [6]:
for dataset in combine:
    dataset['Title'] = dataset.Name.str.extract(' ([A-Za-z]+)\.',\
                                                expand=False)

In [7]:
pd.crosstab(train_df['Title'], train_df['Sex'])

Sex       female  male
Title                 
Capt           0     1
Col            0     2
Countess       1     0
Don            0     1
Dr             1     6
Jonkheer       0     1
Lady           1     0
Major          0     2
Master         0    40
Miss         182     0
Mlle           2     0
Mme            1     0
Mr             0   517
Mrs          125     0
Ms             1     0
Rev            0     6
Sir            0     1

In [8]:
# same for test set
pd.crosstab(test_df['Title'], test_df['Sex'])

Sex     female  male
Title               
Col          0     2
Dona         1     0
Dr           0     1
Master       0    21
Miss        78     0
Mr           0   240
Mrs         72     0
Ms           1     0
Rev          0     2

In [9]:
# We see common titles like Miss, Mrs, Mr, Master are dominant, we will
# correct some Titles to standard forms and replace the rarest titles 
# with single name 'Rare'

for dataset in combine:
    dataset['Title'] = dataset['Title'].\
                  replace(['Lady', 'Countess','Capt', 'Col', 'Don', 'Dr',\
                 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')

    dataset['Title'] = dataset['Title'].replace('Mlle', 'Miss') #Mademoiselle
    dataset['Title'] = dataset['Title'].replace('Ms', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Mme', 'Mrs') #Madame

In [10]:
# Now that we have more logical titles, and a few groups
# we can plot the survival chance for each title

train_df[['Title', 'Survived']].groupby(['Title']).mean()

Survived
Title           
Master  0.575000
Miss    0.702703
Mr      0.156673
Mrs     0.793651
Rare    0.347826

In [11]:
# Title dummy mapping
for dataset in combine:
    binary_encoded = pd.get_dummies(dataset.Title)
    newcols = binary_encoded.columns
    dataset[newcols] = binary_encoded

train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch     Fare Embarked Title  Master  Miss  Mr  Mrs  Rare  
0      0   7.2500        S    Mr       0     0   1    0     0  
1      0  71.2833        C   Mrs       0     0   0    1     0  
2      0   7.9250        S  Miss       0     1   0    0     0  
3      0  53.1000        S   Mrs       0     0   0    1     0  
4      0   8.0500        S    Mr       0     0   1    0     0

In [12]:
train_df = train_df.drop(['Name', 'Title', 'PassengerId'], axis=1)
test_df = test_df.drop(['Name', 'Title'], axis=1)
combine = [train_df, test_df]
train_df.shape, test_df.shape

((891, 13), (418, 13))

In [13]:
# Map Sex to binary categories
for dataset in combine:
    dataset['Sex'] = dataset['Sex'] \
    .map( {'female': 1, 'male': 0} ).astype(int)

train_df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked  Master  Miss  \
0         0       3    0  22.0      1      0   7.2500        S       0     0   
1         1       1    1  38.0      1      0  71.2833        C       0     0   
2         1       3    1  26.0      0      0   7.9250        S       0     1   
3         1       1    1  35.0      1      0  53.1000        S       0     0   
4         0       3    0  35.0      0      0   8.0500        S       0     0   

   Mr  Mrs  Rare  
0   1    0     0  
1   0    1     0  
2   0    0     0  
3   0    1     0  
4   1    0     0

In [14]:
guess_ages = np.zeros((2,3),dtype=int) #initialize
guess_ages

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
# Fill the NA's for the Age columns
# with "qualified guesses"

for idx,dataset in enumerate(combine):
    if idx==0:
        print('Working on Training Data set\n')
    else:
        print('-'*35)
        print('Working on Test Data set\n')
    
    print('Guess values of age based on sex and pclass of the passenger...')
    for i in range(0, 2):
        for j in range(0,3):
            guess_df = dataset[(dataset['Sex'] == i) \
                        &(dataset['Pclass'] == j+1)]['Age'].dropna()

            # Extract the median age for this group
            # (less sensitive) to outliers
            age_guess = guess_df.median()
          
            # Convert random age float to int
            guess_ages[i,j] = int(age_guess)
    
            
    print('Guess_Age table:\n',guess_ages)
    print ('\nAssigning age values to NAN age values in the dataset...')
    
    for i in range(0, 2):
        for j in range(0, 3):
            dataset.loc[ (dataset.Age.isnull()) & (dataset.Sex == i) \
                    & (dataset.Pclass == j+1),'Age'] = guess_ages[i,j]
                    

    dataset['Age'] = dataset['Age'].astype(int)
    print()
print('Done!')
train_df.head()

Working on Training Data set

Guess values of age based on sex and pclass of the passenger...
Guess_Age table:
 [[40 30 25]
 [35 28 21]]

Assigning age values to NAN age values in the dataset...

-----------------------------------
Working on Test Data set

Guess values of age based on sex and pclass of the passenger...
Guess_Age table:
 [[42 28 24]
 [41 24 22]]

Assigning age values to NAN age values in the dataset...

Done!


Survived  Pclass  Sex  Age  SibSp  Parch     Fare Embarked  Master  Miss  \
0         0       3    0   22      1      0   7.2500        S       0     0   
1         1       1    1   38      1      0  71.2833        C       0     0   
2         1       3    1   26      0      0   7.9250        S       0     1   
3         1       1    1   35      1      0  53.1000        S       0     0   
4         0       3    0   35      0      0   8.0500        S       0     0   

   Mr  Mrs  Rare  
0   1    0     0  
1   0    1     0  
2   0    0     0  
3   0    1     0  
4   1    0     0

In [16]:
# Split into age bands and look at survival rates
train_df['AgeBand'] = pd.cut(train_df['Age'], 5)
train_df[['AgeBand', 'Survived']].groupby(['AgeBand'], as_index=False)\
                    .mean().sort_values(by='AgeBand', ascending=True)

AgeBand  Survived
0  (-0.08, 16.0]  0.550000
1   (16.0, 32.0]  0.337374
2   (32.0, 48.0]  0.412037
3   (48.0, 64.0]  0.434783
4   (64.0, 80.0]  0.090909

In [17]:
# Change Age column to
# map Age ranges (AgeBands) to integer values of categorical type 
for dataset in combine:    
    dataset.loc[ dataset['Age'] <= 16, 'Age'] = 0
    dataset.loc[(dataset['Age'] > 16) & (dataset['Age'] <= 32), 'Age'] = 1
    dataset.loc[(dataset['Age'] > 32) & (dataset['Age'] <= 48), 'Age'] = 2
    dataset.loc[(dataset['Age'] > 48) & (dataset['Age'] <= 64), 'Age'] = 3
    dataset.loc[ dataset['Age'] > 64, 'Age']=4
train_df.head()

# Note we could just run 
# dataset['Age'] = pd.cut(dataset['Age'], 5,labels=[0,1,2,3,4])

Survived  Pclass  Sex  Age  SibSp  Parch     Fare Embarked  Master  Miss  \
0         0       3    0    1      1      0   7.2500        S       0     0   
1         1       1    1    2      1      0  71.2833        C       0     0   
2         1       3    1    1      0      0   7.9250        S       0     1   
3         1       1    1    2      1      0  53.1000        S       0     0   
4         0       3    0    2      0      0   8.0500        S       0     0   

   Mr  Mrs  Rare       AgeBand  
0   1    0     0  (16.0, 32.0]  
1   0    1     0  (32.0, 48.0]  
2   0    0     0  (16.0, 32.0]  
3   0    1     0  (32.0, 48.0]  
4   1    0     0  (32.0, 48.0]

In [18]:
# remove AgeBand from before
train_df = train_df.drop(['AgeBand'], axis=1)
combine = [train_df, test_df]
train_df.head()

Survived  Pclass  Sex  Age  SibSp  Parch     Fare Embarked  Master  Miss  \
0         0       3    0    1      1      0   7.2500        S       0     0   
1         1       1    1    2      1      0  71.2833        C       0     0   
2         1       3    1    1      0      0   7.9250        S       0     1   
3         1       1    1    2      1      0  53.1000        S       0     0   
4         0       3    0    2      0      0   8.0500        S       0     0   

   Mr  Mrs  Rare  
0   1    0     0  
1   0    1     0  
2   0    0     0  
3   0    1     0  
4   1    0     0

In [19]:
# SibSp = Number of Sibling / Spouses
# Parch = Parents / Children

for dataset in combine:
    dataset['FamilySize'] = dataset['SibSp'] + dataset['Parch'] + 1

    
# Survival chance with FamilySize

train_df[['FamilySize', 'Survived']].groupby(['FamilySize'], as_index=False).mean().sort_values(by='Survived', ascending=False)

FamilySize  Survived
3           4  0.724138
2           3  0.578431
1           2  0.552795
6           7  0.333333
0           1  0.303538
4           5  0.200000
5           6  0.136364
7           8  0.000000
8          11  0.000000

In [20]:
# Binary variable if the person was alone or not

for dataset in combine:
    dataset['IsAlone'] = 0
    dataset.loc[dataset['FamilySize'] == 1, 'IsAlone'] = 1

train_df[['IsAlone', 'Survived']].groupby(['IsAlone'], as_index=False).mean()

IsAlone  Survived
0        0  0.505650
1        1  0.303538

In [21]:
# We will only use the binary IsAlone feature for further analysis

train_df = train_df.drop(['Parch', 'SibSp', 'FamilySize'], axis=1)
test_df = test_df.drop(['Parch', 'SibSp', 'FamilySize'], axis=1)
combine = [train_df, test_df]

train_df.head()

Survived  Pclass  Sex  Age     Fare Embarked  Master  Miss  Mr  Mrs  Rare  \
0         0       3    0    1   7.2500        S       0     0   1    0     0   
1         1       1    1    2  71.2833        C       0     0   0    1     0   
2         1       3    1    1   7.9250        S       0     1   0    0     0   
3         1       1    1    2  53.1000        S       0     0   0    1     0   
4         0       3    0    2   8.0500        S       0     0   1    0     0   

   IsAlone  
0        0  
1        0  
2        1  
3        0  
4        1

In [22]:
# We can also create new features based on intuitive combinations
for dataset in combine:
    dataset['Age*Class'] = dataset.Age * dataset.Pclass

train_df.loc[:, ['Age*Class', 'Age', 'Pclass']].head(8)

Age*Class  Age  Pclass
0          3    1       3
1          2    2       1
2          3    1       3
3          2    2       1
4          6    2       3
5          3    1       3
6          3    3       1
7          0    0       3

In [23]:
# To replace Nan value in 'Embarked', we will use the mode
# in 'Embaraked'. This will give us the most frequent port 
# the passengers embarked from

freq_port = train_df.Embarked.dropna().mode()[0]
freq_port

'S'

In [24]:
# Fill NaN 'Embarked' Values in the datasets
for dataset in combine:
    dataset['Embarked'] = dataset['Embarked'].fillna(freq_port)
    
train_df[['Embarked', 'Survived']].groupby(['Embarked'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.339009

In [25]:
# Create categorical dummy variables for Embarked values
for dataset in combine:
    binary_encoded = pd.get_dummies(dataset.Embarked)
    newcols = binary_encoded.columns
    dataset[newcols] = binary_encoded

    
train_df.head()

Survived  Pclass  Sex  Age     Fare Embarked  Master  Miss  Mr  Mrs  Rare  \
0         0       3    0    1   7.2500        S       0     0   1    0     0   
1         1       1    1    2  71.2833        C       0     0   0    1     0   
2         1       3    1    1   7.9250        S       0     1   0    0     0   
3         1       1    1    2  53.1000        S       0     0   0    1     0   
4         0       3    0    2   8.0500        S       0     0   1    0     0   

   IsAlone  Age*Class  C  Q  S  
0        0          3  0  0  1  
1        0          2  1  0  0  
2        1          3  0  0  1  
3        0          2  0  0  1  
4        1          6  0  0  1

In [26]:
# Fill the NA values in the Fares column with the median
test_df['Fare'].fillna(test_df['Fare'].dropna().median(), inplace=True)
test_df.head()

PassengerId  Pclass  Sex  Age     Fare Embarked  Master  Miss  Mr  Mrs  \
0          892       3    0    2   7.8292        Q       0     0   1    0   
1          893       3    1    2   7.0000        S       0     0   0    1   
2          894       2    0    3   9.6875        Q       0     0   1    0   
3          895       3    0    1   8.6625        S       0     0   1    0   
4          896       3    1    1  12.2875        S       0     0   0    1   

   Rare  IsAlone  Age*Class  C  Q  S  
0     0        1          6  0  1  0  
1     0        0          6  0  0  1  
2     0        1          6  0  1  0  
3     0        1          3  0  0  1  
4     0        0          3  0  0  1

In [27]:
# q cut will find ranges equal to the quantile of the data
train_df['FareBand'] = pd.qcut(train_df['Fare'], 4)
train_df[['FareBand', 'Survived']].groupby(['FareBand'], as_index=False).mean().sort_values(by='FareBand', ascending=True)

FareBand  Survived
0   (-0.001, 7.91]  0.197309
1   (7.91, 14.454]  0.303571
2   (14.454, 31.0]  0.454955
3  (31.0, 512.329]  0.581081

In [28]:
for dataset in combine:
    dataset.loc[ dataset['Fare'] <= 7.91, 'Fare'] = 0
    
    dataset.loc[(dataset['Fare'] > 7.91) & \
                    (dataset['Fare'] <= 14.454), 'Fare'] = 1
    
    dataset.loc[(dataset['Fare'] > 14.454) & \
                    (dataset['Fare'] <= 31), 'Fare']   = 2
    
    dataset.loc[ dataset['Fare'] > 31, 'Fare'] = 3
    
    dataset['Fare'] = dataset['Fare'].astype(int)

train_df = train_df.drop(['FareBand'], axis=1)
combine = [train_df, test_df]

In [29]:
# Drop Embarked
for dataset in combine:
    dataset.drop('Embarked', axis=1, inplace=True)

In [30]:
train_df.head(7)

Survived  Pclass  Sex  Age  Fare  Master  Miss  Mr  Mrs  Rare  IsAlone  \
0         0       3    0    1     0       0     0   1    0     0        0   
1         1       1    1    2     3       0     0   0    1     0        0   
2         1       3    1    1     1       0     1   0    0     0        1   
3         1       1    1    2     3       0     0   0    1     0        0   
4         0       3    0    2     1       0     0   1    0     0        1   
5         0       3    0    1     1       0     0   1    0     0        1   
6         0       1    0    3     3       0     0   1    0     0        1   

   Age*Class  C  Q  S  
0          3  0  0  1  
1          2  1  0  0  
2          3  0  0  1  
3          2  0  0  1  
4          6  0  0  1  
5          3  0  1  0  
6          3  0  0  1

In [31]:
test_df.head(7)

PassengerId  Pclass  Sex  Age  Fare  Master  Miss  Mr  Mrs  Rare  IsAlone  \
0          892       3    0    2     0       0     0   1    0     0        1   
1          893       3    1    2     0       0     0   0    1     0        0   
2          894       2    0    3     1       0     0   1    0     0        1   
3          895       3    0    1     1       0     0   1    0     0        1   
4          896       3    1    1     1       0     0   0    1     0        0   
5          897       3    0    0     1       0     0   1    0     0        1   
6          898       3    1    1     0       0     1   0    0     0        1   

   Age*Class  C  Q  S  
0          6  0  1  0  
1          6  0  0  1  
2          6  0  1  0  
3          3  0  0  1  
4          3  0  0  1  
5          0  0  0  1  
6          3  0  1  0

In [32]:
X = train_df.drop("Survived", axis=1)

In [33]:
y = train_df.Survived

In [34]:
print(X.shape, y.shape)

(891, 14) (891,)


In [35]:
np.random.seed(1337) # set random seed for reproducibility

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)

(712, 14) (712,)
(179, 14) (179,)


In [36]:
logreg = LogisticRegression() # instantiate
logreg.fit(X_train, y_train) # fit
y_pred = logreg.predict(X_val) # predict
acc_log = round(logreg.score(X_val, y_val) * 100, 2) # evaluate
acc_log

78.21

In [37]:
# Support Vector Machines

svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_val)
acc_svc = round(svc.score(X_val, y_val) * 100, 2)
acc_svc

84.36

In [38]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_val)
acc_knn = round(knn.score(X_val, y_val) * 100, 2)
acc_knn

79.33

In [40]:
X_test_new = test_df.drop("PassengerId", axis=1)
X_test_new.shape

(418, 14)

In [48]:
#use SVC to predict  whether the passenger  (892 to 1309) will be survived or not 
y_pred_new = svc.predict(X_test_new)
y_pred_new

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [49]:
finalresult = pd.DataFrame({'PassengerId': test_df['PassengerId']  , 'Survived':y_pred_new })

In [51]:
finalresult.set_index('PassengerId' , inplace = True)

In [52]:
finalresult

Survived
PassengerId          
892                 0
893                 0
894                 0
895                 0
896                 1
897                 0
898                 1
899                 0
900                 1
901                 0
902                 0
903                 0
904                 1
905                 0
906                 1
907                 1
908                 0
909                 0
910                 1
911                 0
912                 0
913                 1
914                 1
915                 0
916                 1
917                 0
918                 1
919                 0
920                 0
921                 0
...               ...
1280                0
1281                0
1282                0
1283                1
1284                0
1285                0
1286                0
1287                1
1288                0
1289                1
1290                0
1291                0
1292                1
1293                0
1294                1
1295                0
1296                0
1297                0
1298                0
1299                0
1300                1
1301                1
1302                1
1303                1
1304                1
1305                0
1306                1
1307                0
1308                0
1309                0

[418 rows x 1 columns]

In [54]:
finalresult.to_csv('titanic_submission.csv')